/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_taobao_tair_jmdb_JMdbNative */

#ifndef _Included_com_taobao_tair_jmdb_JMdbNative
#define _Included_com_taobao_tair_jmdb_JMdbNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_taobao_tair_jmdb_JMdbNative
 * Method:    initialize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_taobao_tair_jmdb_JMdbNative_initialize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_taobao_tair_jmdb_JMdbNative
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_taobao_tair_jmdb_JMdbNative_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_taobao_tair_jmdb_JMdbNative
 * Method:    put
 * Signature: (JS[B[B)V
 */
JNIEXPORT void JNICALL Java_com_taobao_tair_jmdb_JMdbNative_put
  (JNIEnv *, jclass, jlong, jshort, jbyteArray, jbyteArray);

/*
 * Class:     com_taobao_tair_jmdb_JMdbNative
 * Method:    get
 * Signature: (JS[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_taobao_tair_jmdb_JMdbNative_get
  (JNIEnv *, jclass, jlong, jshort, jbyteArray);

/*
 * Class:     com_taobao_tair_jmdb_JMdbNative
 * Method:    delete
 * Signature: (JS[B)V
 */
JNIEXPORT void JNICALL Java_com_taobao_tair_jmdb_JMdbNative_delete
  (JNIEnv *, jclass, jlong, jshort, jbyteArray);

/*
 * Class:     com_taobao_tair_jmdb_JMdbNative
 * Method:    capacity
 * Signature: (JSJ)V
 */
JNIEXPORT void JNICALL Java_com_taobao_tair_jmdb_JMdbNative_capacity
  (JNIEnv *, jclass, jlong, jshort, jlong);

/*
 * Class:     com_taobao_tair_jmdb_JMdbNative
 * Method:    datasize
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_com_taobao_tair_jmdb_JMdbNative_datasize
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     com_taobao_tair_jmdb_JMdbNative
 * Method:    usage
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_com_taobao_tair_jmdb_JMdbNative_usage
  (JNIEnv *, jclass, jlong, jshort);

#ifdef __cplusplus
}
#endif
#endif
